### ISSUE TITLE
About App website link points to 404 page

### ISSUE THREAD

**Issue by tollfree** [bepass-org/oblivion-desktop#588] opened 2024-10-18 16:30 UTC
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

The website link on 'About App' page **ircf.space** that actually https://ircf.space/contacts.php is points to 404 page

Oblivion-desktop v1.10.3

### Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟

1. Go to **About App** app page
2. Click on **Website — ircf.space**

### Relevant log output | لاگ برنامه

```shell
no logs needed
```

**Comment by ircfspace** [comment] 2024-10-18 16:36
Hi,
Thank you for your feedback.  

This issue has been resolved in the ongoing changes for the TUN branch and will be fixed in the next update.  
The issue is related to the site's address change, and the correct address is:  
https://ircf.space/contacts

**Closed by ircfspace** 2024-10-18 16:36 UTC
